### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by mdavis-xyz** [AntoineCezar/timeoutcontext#11]
Steps to reproduce:

* Python 3.12.3
* Create a new virtual environment
* `pip install timeoutcontext`
* `python3 -c "from timeoutcontext import timeout"`

Expected behavior:

Import runs without error.

Actual behavior:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.12/site-packages/timeoutcontext/__init__.py", line 3, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Details:

timeoutcontext version 1.2.0

**Comment by SmirnGreg** [comment]
`pkg_resources` are deprecated: https://setuptools.pypa.io/en/latest/pkg_resources.html

The replacement could be https://docs.python.org/3/library/importlib.metadata.html#importlib.metadata.version. Its backport  https://github.com/python/importlib_metadata is not FOSS though.

Maybe it could do importlib.metadata.version on python3.8+ and keep old behavior for older versions of python?

@AntoineCezar would it help you if I prepare a merge request with those changes?

**Comment by AntoineCezar** [comment]
Hello,

Thanks for the feedback. I did not think this package still had users and was about to archive the repository.

I will soon push an update with fixes.
